(function(){
  'use strict';
  const model=window.CNCLabModel,$=id=>document.getElementById(id),key='cnc-lab-v1';
  let task=null,plan=null,hints=0,assisted=false,checked=false,view='target',drafts={},onComplete=()=>{},viewer;
  const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
  try{const raw=JSON.parse(localStorage.getItem(key)||'{}');for(const t of model.tasks){if(model.validate(t,raw[t.id]?.plan))drafts[t.id]=raw[t.id];}}catch{}
  function save(){if(!task)return;drafts[task.id]={plan,assisted,hints};try{localStorage.setItem(key,JSON.stringify(drafts));}catch{$('storage-note').textContent='Хранилище недоступно: изменения останутся только до закрытия страницы';}}
  function read(){const numeric=id=>$(id).value.trim()===''?NaN:Number($(id).value);return {offset:numeric('lab-offset'),rpm:numeric('lab-rpm'),diagnosis:$('lab-diagnosis').value,operations:plan.operations.map(o=>{const card=document.querySelector(`[data-op="${o.id}"]`),p={id:o.id,endDiameter:null};for(const k of ['diameter','length','passes','feed','endDiameter','tool']){const f=card.querySelector(`[data-field="${k}"]`);if(f)p[k]=k==='tool'?f.value:f.value.trim()===''?NaN:Number(f.value);}return p;})};}
  function showGeometry(){if(!viewer)return;const valid=model.validate(task,plan);viewer.set(model.profile(task,view==='result'&&valid?plan:null),view==='result'?(valid?'Размеры по вашим настройкам':'Заполните поля — показана цель'):'Целевая деталь');$('lab-target').setAttribute('aria-pressed',String(view==='target'));$('lab-result').setAttribute('aria-pressed',String(view==='result'));}
  function changed(){plan=read();checked=false;$('lab-finish').disabled=true;$('lab-feedback').className='lab-feedback';$('lab-feedback').textContent='Маршрут изменён. Проверьте его перед выполнением.';showGeometry();save();}
  function field(card,label,key,value,min,max,step){const wrap=node('label',label,'field'),f=node('input');f.type='number';f.min=min;f.max=max;f.step=step;f.value=value;f.dataset.field=key;f.setAttribute('aria-label',card.dataset.title+': '+label);wrap.append(f);card.querySelector('.op-fields').append(wrap);}
  function renderRows(){const list=$('lab-operations');list.replaceChildren();plan.operations.forEach((o,i)=>{const spec=task.operations.find(s=>s.id===o.id),card=node('article',undefined,'operation-card');card.dataset.op=o.id;card.dataset.title=spec.title;const head=node('div',undefined,'op-heading');head.append(node('h3',`${i+1}. ${spec.title}`));const moves=node('div');for(const [direction,label] of [[-1,'Раньше'],[1,'Позже']]){const b=node('button',label);b.type='button';b.className='button secondary';b.setAttribute('aria-label',`${spec.title}: ${label}`);b.disabled=i+direction<0||i+direction>=plan.operations.length;b.addEventListener('click',()=>{plan=read();[plan.operations[i],plan.operations[i+direction]]=[plan.operations[i+direction],plan.operations[i]];renderRows();changed();});moves.append(b);}head.append(moves);card.append(head);
      card.append(node('p',`Съём ≤ ${spec.maxDepth} мм/радиус · подача ${spec.feed[0]}–${spec.feed[1]} мм/об`,'op-limit'));const fields=node('div',undefined,'op-fields');card.append(fields);const label=node('label','Инструмент','field'),select=node('select');select.dataset.field='tool';select.setAttribute('aria-label',`${spec.title}: Инструмент`);for(const [v,t] of Object.entries(model.tools)){const opt=node('option',t);opt.value=v;select.append(opt);}select.value=o.tool;label.append(select);fields.append(label);
      field(card,spec.kind==='groove'?'Диаметр дна, мм':spec.endDiameter?'Начальный Ø, мм':'Диаметр X, мм','diameter',o.diameter,1,60,.1);
      if(spec.endDiameter)field(card,'Конечный Ø, мм','endDiameter',o.endDiameter,1,60,.1);
      field(card,spec.kind==='groove'?'Ширина, мм':'Длина, мм','length',o.length,1,100,.1);field(card,'Проходы','passes',o.passes,1,20,1);field(card,'Подача, мм/об','feed',o.feed,.01,1,.01);list.append(card);
    });}
  function open(t){task=t;const saved=drafts[t.id];plan=saved&&model.validate(t,saved.plan)?structuredClone(saved.plan):model.defaults(t);assisted=saved?.assisted===true;hints=Number.isInteger(saved?.hints)?Math.max(0,Math.min(3,saved.hints)):0;checked=false;view='target';
    $('lab-title').textContent=t.title;$('lab-level').textContent=t.level==='medium'?'Средний уровень':'Сложный уровень';$('lab-brief').textContent=t.brief;$('lab-stock').textContent=`Заготовка Ø${t.stock} × ${t.length} мм${t.bore?' · отверстие Ø'+t.bore:''} · допуск ±0,1 мм`;
    $('lab-dimensions').replaceChildren(...t.operations.map(o=>node('li',`${o.title}: ${o.endDiameter?'Ø'+o.diameter+' → Ø'+o.endDiameter:'Ø'+o.diameter} × ${o.length} мм${o.kind==='groove'?' · начало в 12 мм от левого торца':''}`)));
    $('lab-offset').value=plan.offset;$('lab-rpm').value=plan.rpm;$('lab-diagnosis').value=plan.diagnosis;$('lab-diagnosis-label').hidden=!t.diagnosis;$('lab-rpm-range').textContent=`${t.rpm[0]}–${t.rpm[1]} об/мин`;
    $('lab-finish').disabled=true;$('lab-feedback').className='lab-feedback';$('lab-feedback').textContent='Составьте маршрут, затем проверьте настройки и выполните его.';$('lab-hint-text').textContent=hints?t.hints[hints-1]:'Подсказки открываются постепенно. Попробуйте сначала самостоятельно.';$('lab-hint').disabled=hints===3;$('lab-hint-count').textContent=`${hints} / 3`;
    renderRows();showGeometry();
  }
  function check(){plan=read();const r=model.evaluate(task,plan);checked=r.success;if(!r.success)assisted=true;const box=$('lab-feedback');box.className='lab-feedback '+(r.success?'success':'error');box.replaceChildren(node('strong',r.success?'Маршрут готов к выполнению':'Исправьте маршрут'));if(r.success)box.append(node('p','Размеры, режимы и порядок операций соответствуют заданию.'));else{const list=node('ul');r.errors.forEach(e=>list.append(node('li',e)));box.append(list);}$('lab-finish').disabled=!checked;save();return r;}
  function init(done){onComplete=done;viewer=new window.PartViewer($('lab-viewer'));$('lab-operations').addEventListener('input',changed);for(const id of ['lab-offset','lab-rpm','lab-diagnosis'])$(id).addEventListener('input',changed);
    $('lab-check').addEventListener('click',check);$('lab-finish').addEventListener('click',()=>{if(!checked||!model.evaluate(task,read()).success)return;onComplete(task.id,assisted);$('lab-feedback').className='lab-feedback success';$('lab-feedback').replaceChildren(node('strong','Деталь принята — задание выполнено'),node('p',`${assisted?'С помощью подсказок и разбора.':'Самостоятельно.'} Проверены ${plan.operations.length} операции. Это расчётная проверка маршрута, без симуляции движения станка.`));view='result';showGeometry();$('lab-finish').disabled=true;});
    $('lab-hint').addEventListener('click',()=>{assisted=true;hints=Math.min(3,hints+1);$('lab-hint-text').textContent=task.hints[hints-1];$('lab-hint-count').textContent=`${hints} / 3`;$('lab-hint').disabled=hints===3;save();});
    $('lab-reset').addEventListener('click',()=>{delete drafts[task.id];open(task);save();});for(const v of ['target','result'])$('lab-'+v).addEventListener('click',()=>{view=v;showGeometry();});
  }
  window.CNCLabUI={init,open,check,readState:()=>({task:task?.id,plan:task?read():null,checked})};
})();
