(function(){
  'use strict';
  const $=id=>document.getElementById(id),process=window.CNCProcess,lab=window.CNCLabModel;
  let t,p,viewer,steps=[],frames=[],cursor=0,reached=0,playing=false,raf=null,disabled=false,readOnly=false,done=()=>{},persist=()=>{},logs=[],measurement=null;
  const fmt=n=>n.toLocaleString('ru-RU',{maximumFractionDigits:2,minimumFractionDigits:2});
  function pause(){if(raf!==null)cancelAnimationFrame(raf);raf=null;playing=false;render();}
  function state(){return frames[cursor]||process.stock(t);}
  function render(){if(!t)return;$('lab-finish').textContent=playing?'Пауза':cursor===steps.length&&steps.length?'Повторить обработку':cursor?'Продолжить обработку':'Запустить обработку';$('sim-step').disabled=playing||disabled;$('sim-back').disabled=playing||!cursor||disabled;$('sim-stage').disabled=playing||!reached;$('sim-stage').max=reached;$('sim-stage').value=cursor;$('sim-status').textContent=cursor?`${cursor} / ${steps.length} · ${steps[cursor-1]?.title} · проход ${steps[cursor-1]?.pass} из ${steps[cursor-1]?.total}`:'Исходная заготовка';$('gauge-read').disabled=playing||disabled;document.querySelectorAll('#lab-operations input,#lab-operations select,#lab-operations button,#lab-global-fields input').forEach(e=>{if(e.tagName!=='BUTTON')e.disabled=playing||readOnly;});for(const id of ['lab-offset','lab-rpm','lab-diagnosis','lab-check','lab-reset'])$(id).disabled=playing||readOnly;}
  function show(){measurement=null;$('gauge-record').disabled=true;$('gauge-value').textContent='—';viewer.measurement=null;viewer.set(state(),cursor?`После прохода ${cursor} / ${steps.length}`:'Исходная заготовка');$('lab-target').setAttribute('aria-pressed','false');$('lab-result').setAttribute('aria-pressed','true');render();}
  function prepare(){if(disabled)return false;p=window.CNCLabUI.getPlan();try{steps=process.timeline(t,p);frames=[process.stock(t)];for(const step of steps)frames.push(process.cut(t,p,frames.at(-1),step));return true;}catch(e){$('lab-feedback').textContent=e.message;$('lab-feedback').className='lab-feedback error';return false;}}
  function complete(){playing=false;raf=null;render();persist();if(cursor===steps.length&&steps.length){const r=lab.evaluate(t,p);if(r.success)done();else{$('lab-feedback').className='lab-feedback error';$('lab-feedback').textContent='Обработка завершена с ошибками. Измерьте деталь и проверьте маршрут.';}}}
  function advance(){if(disabled||playing||!prepare())return;if(cursor>=steps.length){cursor=0;reached=0;logs=[];renderLogs();}cursor++;reached=Math.max(reached,cursor);show();complete();}
  function run(){if(disabled)return;if(playing){pause();show();persist();return;}if(!prepare())return;if(cursor>=steps.length){cursor=0;reached=0;logs=[];renderLogs();}playing=true;render();let began=null;const duration=matchMedia('(prefers-reduced-motion: reduce)').matches?200:1000;
    function tick(now){if(!playing)return;if(began===null)began=now;const f=Math.min(1,(now-began)/duration),step=steps[cursor];viewer.measurement=null;viewer.set(process.cut(t,p,frames[cursor],{...step,pass:step.pass-1+f}),`${step.title} · проход ${step.pass} / ${step.total}`);if(f===1){cursor++;reached=cursor;show();persist();if(cursor===steps.length){complete();return;}began=now;}raf=requestAnimationFrame(tick);}raf=requestAnimationFrame(tick);
  }
  function renderLogs(){const list=$('gauge-log');list.replaceChildren();for(const m of logs){const li=document.createElement('li');li.textContent=`Проход ${m.stage}: ${m.title}, ${fmt(m.reading)} мм · ${m.instrument==='micrometer'?'микрометр':'штангенциркуль'} · ${m.correct?'вывод верный':'вывод неверный'}`;list.append(li);}}
  function readGauge(){if(playing||disabled)return;show();try{measurement=process.measure(t,state(),$('gauge-surface').value,Number($('gauge-position').value)/100,$('gauge-tool').value);viewer.measurement=measurement;viewer.draw();$('gauge-value').textContent=fmt(measurement.reading)+' мм';$('gauge-target').textContent=`Цель в этой точке: ${fmt(measurement.target)} ±0,10 мм. Цена деления: ${measurement.resolution} мм.`;$('gauge-message').textContent='Сравните размер с допуском и запишите свой вывод.';$('gauge-record').disabled=false;}catch(e){measurement=null;$('gauge-value').textContent='—';$('gauge-message').textContent=e.message;$('gauge-record').disabled=true;}}
  function changed(){pause();cursor=0;reached=0;steps=[];frames=[];logs=[];measurement=null;viewer.measurement=null;$('gauge-value').textContent='—';$('gauge-target').textContent='Измеряется текущая заготовка после выполненных проходов.';$('gauge-message').textContent='';$('gauge-record').disabled=true;renderLogs();render();}
  function open(task,partViewer,options={}){pause();t=task;viewer=partViewer;disabled=!!options.exam;readOnly=!!options.readonly;cursor=0;reached=0;steps=[];frames=[];logs=[];measurement=null;viewer.measurement=null;done=options.done||(()=>{});persist=options.persist||(()=>{});
    const select=$('gauge-surface');select.replaceChildren(...process.surfaces(t).map(s=>{const o=document.createElement('option');o.value=s.id;o.textContent=s.title+(s.kind==='bore'?' · внутри':' · снаружи');return o;}));$('gauge-position').value=50;$('gauge-record').disabled=true;$('gauge-value').textContent='—';$('gauge-target').textContent='Измеряется текущая заготовка после выполненных проходов.';$('gauge-message').textContent='';
    $('simulation-controls').hidden=disabled;$('measurement-panel').hidden=disabled;if(!disabled&&options.saved&&prepare()){const n=options.saved.cursor;if(Number.isInteger(n)&&n>=0&&n<=steps.length)cursor=reached=n;}renderLogs();render();}
  function init(){
    $('lab-viewer').insertAdjacentHTML('afterend','<div id="simulation-controls" class="simulation-controls"><div class="lab-actions"><button id="sim-back" type="button" class="button secondary">Предыдущий проход</button><button id="sim-step" type="button" class="button secondary">Следующий проход</button></div><label>Осмотр выполненных проходов<input id="sim-stage" type="range" min="0" max="0" value="0" step="1"></label><p id="sim-status" aria-live="polite"></p></div><section id="measurement-panel" class="measurement-panel" aria-labelledby="gauge-title"><h3 id="gauge-title">Измерение детали</h3><div class="field-row"><label class="field">Поверхность<select id="gauge-surface"></select></label><label class="field">Инструмент<select id="gauge-tool"><option value="caliper">Штангенциркуль · 0,1 мм</option><option value="micrometer">Наружный микрометр · 0,01 мм</option></select></label></div><label class="field">Положение вдоль поверхности, %<input id="gauge-position" type="range" min="0" max="100" value="50"></label><button id="gauge-read" type="button" class="button secondary">Измерить</button><output id="gauge-value">—</output><p id="gauge-target"></p><label class="field">Мой вывод<select id="gauge-verdict"><option value="ok">В допуске</option><option value="large">Размер больше допуска</option><option value="small">Размер меньше допуска</option></select></label><button id="gauge-record" type="button" class="button secondary" disabled>Записать замер</button><p id="gauge-message" aria-live="polite"></p><ol id="gauge-log"></ol><p class="small-note">Учебная модель прибора: округление до цены деления, без случайной погрешности. Пограничный размер уточняйте более точным прибором.</p></section>');
    $('sim-step').addEventListener('click',advance);$('sim-back').addEventListener('click',()=>{if(!playing&&cursor){cursor--;show();}});$('sim-stage').addEventListener('input',()=>{if(!playing){cursor=Number($('sim-stage').value);show();}});$('gauge-read').addEventListener('click',readGauge);
    for(const id of ['gauge-surface','gauge-position','gauge-tool'])$(id).addEventListener('input',()=>{measurement=null;viewer.measurement=null;viewer.draw();$('gauge-record').disabled=true;$('gauge-value').textContent='—';});
    $('gauge-record').addEventListener('click',()=>{if(!measurement||playing||disabled)return;const correct=$('gauge-verdict').value===measurement.verdict;logs.unshift({...measurement,correct,stage:cursor});logs=logs.slice(0,12);$('gauge-message').textContent=correct?'Верно. Замер записан.':'Вывод неверный. Сравните размер с границами допуска.';renderLogs();$('gauge-record').disabled=true;});
  }
  window.CNCLabSession={init,open,changed,run,pause,show,state:()=>({cursor,reached,playing}),snapshot:()=>({cursor}),active:()=>playing};
})();
