(function(){
  'use strict';
  const $=id=>document.getElementById(id),model=window.CNCRouteExam,lab=window.CNCLabModel,key='cnc-route-exams-v1';
  let active=null,history=[],report=null,opened=null,notify=()=>{},review=()=>{};
  const name=l=>l==='medium'?'Средний':'Сложный',node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
  try{const s=JSON.parse(localStorage.getItem(key)||'null');if(s){active=model.restore(s.active);history=(Array.isArray(s.history)?s.history:[]).map(model.restore).filter(e=>e?.answers.length===2).slice(0,10);if(active?.answers.length===2){if(!history.some(e=>e.at===active.at))history.unshift(active);active=null;}if(['easy','medium','hard'].includes(s.level))$('exam-level').value=s.level;if(active)$('exam-level').value=active.level;report=history[0]||null;}}catch{}
  function save(){try{localStorage.setItem(key,JSON.stringify({active,history,level:$('exam-level').value}));}catch{$('storage-note').textContent='Хранилище недоступно: экзамен сохраняется только до закрытия страницы';}}
  function start(){if(active)return;const seed=crypto.getRandomValues(new Uint32Array(1))[0];active=model.create($('exam-level').value,seed);report=null;opened=null;save();notify();renderHistory();}
  function submit(){if(!active||active.answers.length!==active.index)return;try{active=model.submit(active,window.CNCLabUI.getPlan());if(active.answers.length===2){history.unshift(active);history=history.slice(0,10);report=active;active=null;}opened=null;save();notify();renderHistory();}catch(e){$('lab-feedback').textContent=e.message;}}
  function next(){if(!active)return;active=model.advance(active);opened=null;save();notify();}
  function render(){
    if(report?.level!==$('exam-level').value)report=history.find(h=>h.level===$('exam-level').value)||null;
    $('workspace').hidden=true;$('exam-results').hidden=true;$('lab-workspace').hidden=!active;$('route-exam-results').hidden=!report||!!active;$('exam-start').hidden=!!active;$('exam-start').textContent=report?'Новый вариант':'Начать экзамен';$('exam-counter').hidden=!active;$('exam-counter').textContent=active?`Деталь ${active.index+1} из 2`:'';$('exam-title').textContent=`${name($('exam-level').value)} экзамен${active?' идёт':': 2 детали'}`;
    $('route-submit').hidden=!active||active.answers.length!==active.index;$('route-next').hidden=!active||active.answers.length===active.index;
    if(active){const k=`${active.at}/${active.index}/${active.answers.length}`;if(opened!==k){const t=model.taskFor(active.level,active.seed,active.index),accepted=active.answers.length>active.index;window.CNCLabUI.open(t,{exam:true,readonly:accepted,plan:accepted?active.answers[active.index]:active.draft||lab.defaults(t),onDraft:p=>{if(active&&active.answers.length===active.index){active.draft=p;save();}}});opened=k;}$('lab-feedback').className='lab-feedback';$('lab-feedback').textContent=active.answers.length>active.index?'Ответ сохранён. Оценка появится после второй детали.':'Одна сдача на деталь. Подсказки, измерения и пробная обработка в экзамене отключены.';}
    else if(report)renderReport();
  }
  function renderReport(){const result=model.grade(report),box=$('route-exam-results');box.replaceChildren();const header=node('div',undefined,'panel-heading');header.append(node('h2',`${name(report.level)} экзамен — результат`));const exp=node('button','Скачать разбор','button secondary');exp.type='button';exp.addEventListener('click',exportReport);header.append(exp);box.append(header);const summary=node('div',undefined,'exam-summary');summary.append(node('strong',`${result.score} / 100`),node('p','Средний балл двух деталей. Подсказки: 0. Каждая категория оценивается отдельно.'));box.append(summary);
    for(const a of result.answers){const row=node('article',undefined,'review-row');row.append(node('h3',`${a.task.title} · ${a.result.score} / 100`),node('p',`Точность ${a.result.parts.accuracy}/40 · Технология ${a.result.parts.technology}/25 · Порядок ${a.result.parts.order}/15 · Экономичность ${a.result.parts.economy}/20`),node('p',`Лишние проходы: ${a.result.extra}. За каждый снимаются 2 балла экономичности (до 20).`));row.append(node('p',`Ответ: коррекция ${a.plan.offset} мм, обороты ${a.plan.rpm}. Порядок: ${a.plan.operations.map(o=>a.task.operations.find(s=>s.id===o.id).title).join(' → ')}.`));for(const e of a.result.errors)row.append(node('p',e,'review-error'));if(a.result.success)row.append(node('p','Все условия детали соблюдены.'));const b=node('button','Повторить тему','button secondary');b.type='button';b.addEventListener('click',()=>review(a.task.id));row.append(b);box.append(row);}
  }
  function renderHistory(blocked=false){const box=$('route-history');box.replaceChildren();for(const h of history){const row=node('div',undefined,'history-row');row.append(node('span',`${name(h.level)} · ${new Date(h.at).toLocaleString('ru-RU')}`),node('strong',`${model.grade(h).score} / 100`));const b=node('button','Разбор','button secondary');b.type='button';b.disabled=blocked||!!active;b.addEventListener('click',()=>{report=h;$('exam-level').value=h.level;opened=null;save();notify(true);});row.append(b);box.append(row);}}
  function exportReport(){if(!report)return;const g=model.grade(report),lines=[`${name(report.level)} экзамен: ${g.score}/100`,new Date(report.at).toLocaleString('ru-RU'),'Подсказки: 0',''];for(const a of g.answers){lines.push(a.task.title,`Баллы: ${a.result.score}; точность ${a.result.parts.accuracy}/40; технология ${a.result.parts.technology}/25; порядок ${a.result.parts.order}/15; экономичность ${a.result.parts.economy}/20.`,`Коррекция: ${a.plan.offset}. Обороты: ${a.plan.rpm}. Диагноз: ${a.plan.diagnosis}.`,...a.plan.operations.map(o=>`${o.id}: Ø${o.diameter}${o.endDiameter?' → '+o.endDiameter:''}, L ${o.length}, проходы ${o.passes}, подача ${o.feed}, инструмент ${lab.tools[o.tool]}`),...a.result.errors,'');}const url=URL.createObjectURL(new Blob(['\ufeff'+lines.join('\n')],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='cnc-route-exam.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function init(callback,onReview){notify=callback;review=onReview;const box=document.querySelector('.lab-actions');const submitButton=node('button','Сдать маршрут','button primary');submitButton.id='route-submit';submitButton.type='button';submitButton.hidden=true;submitButton.addEventListener('click',submit);const nextButton=node('button','Следующая деталь','button primary');nextButton.id='route-next';nextButton.type='button';nextButton.hidden=true;nextButton.addEventListener('click',next);document.querySelector('.lab-plan .lab-actions').append(submitButton,nextButton);renderHistory();}
  function hide(){opened=null;$('route-exam-results').hidden=true;$('route-submit').hidden=true;$('route-next').hidden=true;}
  window.CNCRouteExamUI={init,start,render,hide,save,renderHistory,active:()=>!!active,invalidate:()=>{opened=null;},readState:()=>active?{level:active.level,index:active.index,submitted:active.answers.length,plan:active.draft}:null};
})();
