const assert=require('node:assert/strict');
const m=require('../model.js');
const good={x:28,offset:0,feed:.2,rpm:800,tool:'turning'};
assert.equal(m.evaluate(good).success,true);
assert.equal(m.evaluate(good).depth,2);
for(const t of m.tasks)assert.equal(m.evaluate(t.defaults).success,false,t.id+' must start with a teaching error');
assert.equal(m.evaluate({...good,x:30}).errors[0].key,'diameter');
assert.equal(m.evaluate({...good,offset:-4}).actual,24);
assert(m.evaluate({...good,offset:-4}).errors.some(e=>e.key==='depth'));
assert.equal(m.evaluate({...good,x:1,offset:-2}).canAnimate,false);
assert.equal(m.evaluate({...good,tool:'drill'}).canAnimate,false);
assert.equal(m.evaluate({...good,feed:.45}).errors[0].key,'feed');
assert.equal(m.evaluate({...good,feed:NaN}).valid,false);
assert.equal(m.evaluate({...good,rpm:3000}).valid,false);
assert.equal(m.evaluate({...good,feed:.1,rpm:600}).success,true);
assert.equal(m.evaluate({...good,feed:.25,rpm:1000}).success,true);
assert.match(m.mentor({...good,feed:.45},'Что исправить?',true),/подача/);
assert.match(m.mentor(good,'как работает коррекция'),/28/);
console.log('Model checks passed: valid pass, 3 exercises, overcut, collision, tool, bounds, mentor.');
